base:
  project: Diabetes Detection
  random_state: 789456
  target_col: label
  solver: saga
  ### liblinear, newton-cg, sag, saga, lbfgs

load_data:
  raw_dataset_csv: data/raw/pima-indians-diabetes.csv

split_data:
  train_path: data/processed/train_pima-indians-diabetes.csv
  test_path: data/processed/test_pima-indians-diabetes.csv
  test_size: 0.25

model_dir: models

reports:
  train_scores: reports/train_scores.json
  test_scores: reports/test_scores.json
  roc: reports/roc.json
  prc: reports/prc.json
  auc: reports/auc.json
  cm: reports/cm.csv

test_size: 0.25
